spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  graphql:
    cors:
      allow-credentials:

springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true

cors:
  originPatterns: http://localhost:3000,http://localhost:8080
